CREATE TABLE IF NOT EXISTS users (
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CONSTRAINT users_ID_pk PRIMARY KEY (ID),
    CONSTRAINT users_NAME_pk UNIQUE (NAME),
    CONSTRAINT users_EMAIL_pk UNIQUE (NAME)
);